require 'pry'
require 'active_record'
require_relative 'database_config'
require_relative 'models/shop'
require_relative 'models/shop_group'
require_relative 'models/shop_owner'
require_relative 'models/shop_service'
require_relative 'models/group'
require_relative 'models/service'
binding.pry
